name: happy_frances
services:
  bazarr:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 7857M
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Central
      - UMASK=002
    image: ghcr.io/hotio/bazarr:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Bazarr/icon.png
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/bazarr/config
        target: /config
      - type: bind
        source: /mnt/media/subtitles
        target: /mnt/media/subtitles
    ports: []
    devices: []
    cap_add: []
    network_mode: container:gluetun
    container_name: ""
    hostname: ""
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Bazarr/icon.png
  index: /
  is_uncontrolled: false
  port_map: "6767"
  scheme: http
  store_app_id: happy_frances
  title:
    custom: Bazarr
