name: gracious_maxime
services:
  flaresolverr:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 7857M
    environment:
      - CAPTCHA_SOLVER=none
      - LOG_HTML=false
      - LOG_LEVEL=info
      - PORT=8191
      - PROMETHEUS_ENABLED=false
      - PROMETHEUS_PORT=8191
      - TZ=US/Central
    image: ghcr.io/flaresolverr/flaresolverr:latest
    labels:
      icon: https://avatars.githubusercontent.com/u/10577978
    privileged: true
    restart: unless-stopped
    ports: []
    volumes: []
    devices: []
    cap_add: []
    network_mode: container:gluetun
    container_name: ""
    hostname: ""
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://avatars.githubusercontent.com/u/10577978
  index: /
  is_uncontrolled: false
  port_map: "8191"
  scheme: http
  store_app_id: gracious_maxime
  title:
    custom: FlareSolverr
