name: adoring_anuj
services:
  lidarr:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 7857M
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Central
      - UMASK=002
    image: ghcr.io/hotio/lidarr:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/icon.png
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/lidarr/config
        target: /config
      - type: bind
        source: /mnt/media/music
        target: /mnt/media/music
      - type: bind
        source: /mnt/downloads/downloads
        target: /mnt/downloads/downloads
    ports: []
    devices: []
    cap_add: []
    network_mode: container:gluetun
    container_name: ""
    hostname: ""
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/icon.png
  index: /
  is_uncontrolled: false
  port_map: "8686"
  scheme: http
  store_app_id: adoring_anuj
  title:
    custom: Lidarr
